BooksApp/BooksApp.MVC/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using BooksApp.Business.Abstract;
using BooksApp.MVC.Areas.Admin.Models.ViewModels;
//using BooksApp.MVC.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace BooksApp.MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class HomeController : Controller
    {
        private readonly IOrderService _orderService;

        public HomeController(IOrderService orderService)
        {
            _orderService = orderService;
        }

        public async Task<IActionResult> Index()
        {
            var orderList = await _orderService.GetAllOrdersAsync(null, false);
            List<OrderViewModel> orders = orderList.Select(o => new OrderViewModel
            {
                Id = o.Id,
                Address = o.Address,
                City = o.City,
                Phone = o.Phone,
                Email = o.Email,
                FirstName = o.FirstName,
                LastName = o.LastName,
                OrderDate = o.OrderDate,
                OrderItems = o.OrderItems.Select(oi => new OrderItemViewModel
                {
                    OrderItemId = oi.Id,
                    BookId = oi.BookId,
                    BookName = oi.Book.Name,
                    BookUrl = oi.Book.Url,
                    ImageUrl = oi.Book.Images[0].Url,
                    ItemPrice = oi.Price,
                    Quantity = oi.Quantity
                }).ToList()
            }).ToList();
            return View(orders);
        }
        public async Task<IActionResult> SearchOrderByUser(string keyword)
        {
            var orderList = await _orderService.SearchOrderByUser(keyword.ToUpper());
            List<OrderViewModel> orders = orderList.Select(o => new OrderViewModel
            {
                Id = o.Id,
                FirstName = o.FirstName,
                LastName = o.LastName,
                City = o.City,
                Address = o.Address,
                Email = o.Email,
                Phone = o.Phone,
                OrderDate = o.OrderDate,
                OrderItems = o.OrderItems.Select(oi => new OrderItemViewModel
                {
                    OrderItemId = oi.Id,
                    BookId = oi.BookId,
                    BookName = oi.Book.Name,
                    BookUrl = oi.Book.Url,
                    ImageUrl = oi.Book.Images[0].Url,
                    ItemPrice = oi.Price,
                    Quantity = oi.Quantity
                }).ToList()
            }).ToList();
            return View("Index", orders);
        }
    }
}

BooksApp/BooksApp.MVC/Controllers/CartController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using BooksApp.Business.Abstract;
using BooksApp.Core;
using BooksApp.Entity.Concrete;
using BooksApp.Entity.Concrete.Identity;
using BooksApp.MVC.Models.ViewModels;
using Iyzipay;
using Iyzipay.Model;
using Iyzipay.Request;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BooksApp.MVC.Controllers
{
    public class CartController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly ICartService _cartService;
        private readonly ICartItemService _cartItemService;
        private readonly IOrderService _orderService;
        private readonly INotyfService _notyfService;

        public CartController(UserManager<User> userManager, ICartService cartService, ICartItemService cartItemService, IOrderService orderService, INotyfService notyfService)
        {
            _userManager = userManager;
            _cartService = cartService;
            _cartItemService = cartItemService;
            _orderService = orderService;
            _notyfService = notyfService;
        }
        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);
            var cart = await _cartService.GetCartByUserId(userId);
            CartViewModel cartViewModel = new CartViewModel
            {
                CartId = cart.Id,
                CartItems = cart
                    .CartItems
                    .Select(ci => new CartItemViewModel
                    {
                        CartItemId=ci.Id,
                        BookId=ci.BookId,
                        BookName=ci.Book.Name,
                        Quantity=ci.Quantity,
                        BookUrl=ci.Book.Url,
                        ItemPrice=ci.Book.Price,
                        ImageUrl = ci.Book.Images[0].Url
                    }).ToList()
            };
            return View(cartViewModel);
        }
        [HttpPost]
        public IActionResult AddToCart(int Id, int Quantity)
        {
            var userId = _userManager.GetUserId(User);
            _cartService.AddToCart(userId, Id, Quantity);
            _notyfService.Success("Ürün sepetinize başarıyla eklenmiştir");
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> DeleteFromCart(int id)
        {
            var cartItem = await _cartItemService.GetByIdAsync(id);
            _cartItemService.Delete(cartItem);
            
            _notyfService.Information("Ürün sepetten kaldırılmıştır",2);
            return RedirectToAction("Index");
        }
        public IActionResult ClearCart(int id)
        {
            _cartItemService.ClearCart(id);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> ChangeQuantity(CartItemViewModel cartItemViewModel) 
        {
            if (ModelState.IsValid)
            {
                await _cartItemService.ChangeQuantityAsync(cartItemViewModel.CartItemId, cartItemViewModel.Quantity);
            }
            else
            {
                TempData["QuantityMessage"] = "Minimum 1 adet olmalıdır";
            }
            return RedirectToAction("Index");

        }
        [HttpGet]
        public async Task<IActionResult> Checkout()
        {
            var userId = _userManager.GetUserId(User);
            var user = await _userManager.FindByIdAsync(userId);
            var cart = await _cartService.GetCartByUserId(userId);
            OrderViewModel orderViewModel = new OrderViewModel
            {
                FirstName = user.FirstName,
                LastName = user.LastName,
                Address = user.Address,
                City = user.City,
                Phone = user.PhoneNumber,
                Email = user.Email,
                Cart = new CartViewModel
                {
                    CartId=cart.Id,
                    CartItems=cart.CartItems.Select(ci=>new CartItemViewModel
                    {
                        CartItemId=ci.Id,
                        BookId=ci.BookId,
                        BookName=ci.Book.Name,
                        ItemPrice=ci.Book.Price,
                        Quantity=ci.Quantity,
                        ImageUrl = ci.Book.Images[0].Url
                    }).ToList(),
                }
            };
            return View(orderViewModel);
        }
        [HttpPost]
        public async Task<IActionResult> Checkout(OrderViewModel orderViewModel)
        {
            var userId = _userManager.GetUserId(User);
            var cart = await _cartService.GetCartByUserId(userId);
            if (ModelState.IsValid)
            {

                orderViewModel.Cart = new CartViewModel
                {
                    CartId = cart.Id,
                    CartItems = cart.CartItems.Select(ci => new CartItemViewModel
                    {
                        CartItemId = ci.Id,
                        BookId = ci.BookId,
                        BookName = ci.Book.Name,
                        ItemPrice = ci.Book.Price,
                        ImageUrl = ci.Book.Images[0].Url,
                        Quantity = ci.Quantity
                    }).ToList()
                };
                //Normalde burada ÖDEME İŞLEMLERİNİ yaptıracağız.
 
                //2)Eğer kart numarası geçerliyse ve başka sorun yoksa ödemeyi alacağız.
                //3)Ödeme de başarılıysa SATIŞ İŞLEMLERİNİ yapacağız, yani Order'a kayıt!

                //Önce kart numarasını kontrol ediyoruz.
                if (!CardNumberControl(orderViewModel.CardNumber))
                {
                    _notyfService.Error("Geçersiz kart numarası!");
                    return View(orderViewModel);
                }

                Payment payment = PaymentProcess(orderViewModel);
                if (payment.Status == "success")
                {
                    SaveOrder(orderViewModel, userId);
                    _cartItemService.ClearCart(orderViewModel.Cart.CartId);
                    _notyfService.Success("Ödemeniz alınmış ve siparişiniz oluşturulmuştur!");
                    return RedirectToAction("Index", "Home");
                }
                //_notyfService.Error("Bir sorun oluştu!");
            }
            orderViewModel.Cart = new CartViewModel
            {
                CartId = cart.Id,
                CartItems = cart.CartItems.Select(ci => new CartItemViewModel
                {
                    CartItemId = ci.Id,
                    BookId = ci.BookId,
                    BookName = ci.Book.Name,
                    ItemPrice = ci.Book.Price,
                    Quantity = ci.Quantity,
                    ImageUrl = ci.Book.Images[0].Url
                }).ToList()
            };
            return View(orderViewModel);
        }
        
        [NonAction]
        private async void SaveOrder(OrderViewModel orderViewModel, string userId)
        {
            Order order = new Order();
            order.OrderState = EnumOrderState.Unpaid;
            order.OrderType = EnumOrderType.CreditCard;
            order.OrderDate = DateTime.Now;
            order.FirstName = orderViewModel.FirstName;
            order.LastName = orderViewModel.LastName;
            order.NormalizedName=(orderViewModel.FirstName+orderViewModel.LastName).ToUpper();
            order.Phone= orderViewModel.Phone;
            order.Email = orderViewModel.Email;
            order.Address = orderViewModel.Address;
            order.City= orderViewModel.City;
            order.UserId= userId;
            order.OrderItems = new List<Entity.Concrete.OrderItem>();
            foreach (var cartItem in orderViewModel.Cart.CartItems)
            {
                Entity.Concrete.OrderItem orderItem = new Entity.Concrete.OrderItem();
                orderItem.Price = cartItem.ItemPrice;
                orderItem.Quantity = cartItem.Quantity;
                orderItem.BookId = cartItem.BookId;
                order.OrderItems.Add(orderItem);
            }
            await _orderService.CreateAsync(order);
        }
        [NonAction]
        private bool CardNumberControl(string cardNumber)
        {
            #region Açıklamalar
            /* -cardNumber'ı boşluk ve tire'den arındıracağız.
             * -cardNumber uzunluk kontrolünü yapacağız.
             * -Sayısal değer kontrolü yapacağız.
             * -Luhn algoritmasına uygunluğunu test edeceğiz
             */
            #endregion
            cardNumber = cardNumber.Replace("-", "").Replace(" ", "");
            if (cardNumber.Length != 16) return false;
            foreach (var chr in cardNumber)
            {
                if (!Char.IsNumber(chr)) return false;
            }
            int oddTotal = 0;
            int ovenTotal = 0;
            for (int i = 0; i < cardNumber.Length; i+=2)
            {
                int nextOddNumber = Convert.ToInt32(cardNumber[i].ToString());
                int nextOvenNumber = Convert.ToInt32(cardNumber[i + 1].ToString());
                int addedOddNumber = nextOddNumber * 2;
                addedOddNumber = addedOddNumber >= 10 ? addedOddNumber - 9 : addedOddNumber;
                oddTotal += addedOddNumber;
                ovenTotal += nextOvenNumber;
            }
            int total = oddTotal + ovenTotal;
            bool isValidNumber = total % 10 == 0 ? true : false;
            return isValidNumber;
        }
        private Payment PaymentProcess(OrderViewModel orderViewModel)
        {
            #region Payment Options Created
            Options options = new Options();
            options.ApiKey = "sandbox-GE1AGKrFySgl9T8mcd78R3b9zcmPyGcN";
            options.SecretKey = "sandbox-duB9wikGW6YHl4xD1zoeuCajb3alnBdG";
            options.BaseUrl = "https://sandbox-api.iyzipay.com";
            #endregion
            #region Create Payment Request

BooksApp/BooksApp.MVC/ViewComponents/CategoriesViewComponent.cs
using BooksApp.Business.Abstract;
using BooksApp.Data.Concrete.EfCore;
using BooksApp.Entity.Concrete;
using BooksApp.MVC.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Linq.Expressions;

namespace BooksApp.MVC.ViewComponents
{
    public class CategoriesViewComponent : ViewComponent
    {
        private ICategoryService _categoryService;

        public CategoriesViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<Category> categories = await _categoryService.GetCategoriesAsync(true);

            List<CategoryViewModel> categoryViewModelList = new List<CategoryViewModel>();
            foreach (Category category in categories)
            {
                categoryViewModelList.Add(new CategoryViewModel
                {
                    Id = category.Id,
                    Name = category.Name,
                    Description = category.Description,
                    Url = category.Url
                });
            }
            if (RouteData.Values["categoryurl"] != null)
            {
                ViewBag.SelectedCategory = RouteData.Values["categoryurl"];
            }
            return View(categoryViewModelList);
        }
    }
}

BooksApp/BooksApp.MVC/Views/Home/AuthorDetails.cshtml
@model AuthorModel

<div class="row my-5 py-5">
    <div class="col-lg-3 me-4">
        <img class="img-fluid w-100" src="~/images/authors/@Model.ImageUrl" />
    </div>
    <div class="col-lg-5">
        <h4 class="display-6 fs-1 fw-normal text-danger">@Model.Name</h4>
        <ul class="list-group list-group-flush">
            <li class="list-group-item ">
                Doğum Tarihi : @Model.BirthDate.ToShortDateString()
            </li>
            <li class="list-group-item">
                Cinsiyet : @(Model.Gender=="E" ? "Erkek":"Kadın")
            </li>
        </ul>
    </div>
    <div class="col-lg-3 my-0">
        <h6>Yazarın Kitapları</h6>
        @foreach (var book in Model.Books)
        {
            <a 
           asp-area=""
           asp-controller="Home"
           asp-action="BookDetails"
           asp-route-url="@book.Url"
               class="display-6 fs-6 fw-normal  btn btn-outline-danger m-2">
                Kitap Adı : @book.Name
            </a>
        }
    </div>
    <div class="col-md-8 mt-5">
        <h4 class="display-6 fs-4 fw-normal text-danger">Hakkında</h4>
        <p class="fw-normal fs-6">
            @Model.About
        </p>
    </div>
</div>

BooksApp/BooksApp.MVC/Views/Home/BookDetails.cshtml
@model BookModel
<div class="container pt-4">
    <div class="row">
        <div class="col-3">
            <div class="row">
                @foreach (var image in Model.Images)
                {
                    <div class="col-12 pb-3">
                        <img class="w-100" src="/images/books/@image.Url" />
                    </div>
                }

            </div>
        </div>
        <div class="col-5 bg-light p-3">
            <h3 class="display-6 fs-4 fw-normal text-danger">@Model.Name</h3>
            @for (int i = 0; i < Model.Authors.Count; i++)
            {
                <a 
                    asp-area=""
                    asp-controller="Home"
                    asp-action="AuthorDetails"
                    asp-route-url="@Model.Authors[i].Url"
                    class="display-6 fs-6 fw-normal text-primary">
                    @Model.Authors[i].Name 
                    @(i == Model.Authors.Count - 1 ? "" : " | ")
                </a>
            }
            <div class="mt-3">
                @for (int i = 0; i < 5; i++)
                {
                    <i class="fa-regular fa-star text-success fa-xs"></i>
                }
            </div>
            @*Kitap Ayrıntıları*@
            <div class="mt-3">
                <h3 class="display-6 fs-4 fw-normal text-danger mt-2">Kitap Ayrıntıları</h3>
                <h6 class="d-inline">Kategori:</h6>
                @for (int i = 0; i < Model.Categories.Count; i++)
                {
                    <span class="fs-6 text-warning">@Model.Categories[i].Name @(i == Model.Categories.Count - 1 ? "" : ",")</span>
                }
                <div class="row mt-3">
                    <div class="col-6">
                        <div>
                            <h6 class="d-inline">Basım Yılı:</h6>
                            <span class="fs-6">@Model.EditionYear</span>
                        </div>
                        <div>
                            <h6 class="d-inline">Baskı Numarası:</h6>
                            <span class="fs-6">@Model.EditionNumber</span>
                        </div>
                    </div>
                    <div class="col-6">
                        <div>
                            <h6 class="d-inline">Sayfa Sayısı:</h6>
                            <span class="fs-6">@Model.PageCount</span>
                        </div>
                        <div>
                            <h6 class="d-inline">Stok Miktarı:</h6>
                            <span class="fs-6">@Model.Stock</span>
                        </div>
                    </div>
                </div>
            </div>
            @*Kitap Özeti*@
            <h3 class="display-6 fs-4 fw-normal text-danger mt-3">Kitap Özeti</h3>
            <p class="fs-6">@Html.Raw(Model.Summary)</p>
        </div>
        <div class="col-4">
            @*Fiyat Bölümü*@
            <div class="border-1 border-warning border p-3 pb-0">
                <div class="row">
                    <div class="col-6 d-flex justify-content-center align-items-center">
                        <h5 class="fs-3 text-primary">@($"{Model.Price:C2}")</h5>
                    </div>
                    <div class="col-6 text-center">
                        <p class="fs-6 text-center">Tedarik süresi 3-5 gündür.</p>
                        <form asp-area=""
                              asp-controller="Cart"
                              asp-action="AddToCart"
                              method="post">
                            <input type="hidden" asp-for="Id" />
                            <button type="submit" class="btn btn-warning">Sepete Ekle</button>
                        </form>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 text-center">
                        <p class="text-success mb-2 mt-2 fw-bold">300 TL üzeri kargo bedava!</p>
                    </div>
                </div>
            </div>
            @*Yazar Bilgileri*@
            <div>
                <h3 class="bg-warning p-2 fs-6 text-white fw-bold display-6 mt-3">@Model.Authors[0].Name</h3>
                <img class="float-end me-1" src="https://picsum.photos/100/100" />
                <p class="fs-6">@Html.Raw(Model.Authors[0].About)</p>

            </div>
        </div>
    </div>
</div>

BooksApp/BooksApp.MVC/Views/Home/Index.cshtml
@{
    Layout = "_Layout_Index";
}
@model List<BookModel>
@{
    ViewData["Title"] = "Ana Sayfa";
    List<BookModel> books = Model;
}
@*<!-- Slider -->
@await Html.PartialAsync("_SliderPartial")*@
<!-- Products -->
@await Html.PartialAsync("_BooksPartial", books)
<!-- Services -->
@await Html.PartialAsync("_ServicesPartial")

















@*@model List<BookModel>
@{
    ViewData["Title"] = "Ana Sayfa";
    List<BookModel> books = Model;
}
<div class="row">
    <div class="col-md-2 col-sm-2 col-12">
        <h1 class="display-6 fs-4 text-danger fw-normal ps-1">Kategoriler</h1>
        @await Component.InvokeAsync("Categories")
    </div>
    <div class="col-md-10 col-sm-10 col-12">
        <h1 class="display-6 fs-4 text-danger fw-normal ps-1">
            @(ViewBag.SelectedCategoryName==null ? "Tüm Kategoriler" : "Kategori: " + ViewBag.SelectedCategoryName)
        </h1>
        @if (Model.Count() > 0)
        {
            <div class="row g-3">
                @foreach (var book in books)
                {
                    <div class="col-md-3 col-sm-6 col-12">
                        @await Html.PartialAsync("_BookPartial", book)
                    </div>
                }
            </div>
            <div class="mt-2">
                <p>Toplam <span class="text-danger">@books.Count</span> adet kitap listelenmiştir...</p>
            </div>
        }
        else
        {
            @await Html.PartialAsync("_NoRecord","Kitap")
        }

    </div>
</div>
*@