BooksApp/BooksApp.MVC/Areas/Admin/Models/ViewModels/BookViewModel.cs
using BooksApp.Entity.Concrete;

namespace BooksApp.MVC.Areas.Admin.Models.ViewModels
{
    public class BookViewModel
    {
        public int Id { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime ModifiedDate { get; set; }
        public bool IsApproved { get; set; }
        public string Name { get; set; }
        public int? Stock { get; set; }
        public decimal? Price { get; set; }
        public int? PageCount { get; set; }
        public int? EditionYear { get; set; }
        public int? EditionNumber { get; set; }
        public List<CategoryViewModel> Categories { get; set; }
        public List<AuthorViewModel> Authors { get; set; }
        public List<Image> Images { get; set; }
        public string Url { get; set; }
    }
}

BooksApp/BooksApp.MVC/Areas/Admin/Controllers/AuthorsController.cs
using BooksApp.Business.Abstract;
using BooksApp.Core;
using BooksApp.Data.Abstract;
using BooksApp.Data.Concrete.EfCore;
using BooksApp.Entity.Concrete;
using BooksApp.MVC.Areas.Admin.Models.ViewModels;
using BooksApp.MVC.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq.Expressions;

namespace BooksApp.MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class AuthorsController : Controller
    {
        private IAuthorService _authorService;

        public AuthorsController(IAuthorService authorService)
        {
            _authorService = authorService;
        }
        #region Listeleme
        public async Task<IActionResult> Index(AuthorListViewModel authorListViewModel)
        {
            List<Author> authorList = await _authorService.GetAllAuthorsWithBooksAsync(authorListViewModel.ApprovedStatus);
            List<AuthorViewModel> authors = new List<AuthorViewModel>();
            foreach (var author in authorList)
            {
                authors.Add(new AuthorViewModel
                {
                    Id = author.Id,
                    Name = author.Name,
                    IsApproved = author.IsApproved,
                    Url = author.Url,
                    BirthDate=author.BirthDate,
                    Gender=author.Gender,
                    Books = author.BookAuthors.Select(ba=> new BookViewModel
                    {
                        Id=ba.Book.Id,
                        Name=ba.Book.Name,
                        EditionNumber=ba.Book.EditionNumber,
                        EditionYear=ba.Book.EditionYear,
                        Price = ba.Book.Price,
                        PageCount=ba.Book.PageCount
                    }).ToList()
                });
            }
            
            authorListViewModel.Authors = authors;
            return View(authorListViewModel);
        }
        public async Task<IActionResult> GetAuthorsByBook(int id)
        {
            List<Author> authorList = await _authorService.GetAuthorsByBook(id);
            List<AuthorViewModel> authors = new List<AuthorViewModel>();
            foreach (var author in authorList)
            {
                authors.Add(new AuthorViewModel
                {
                    Id = author.Id,
                    Name = author.Name,
                    CreatedDate = author.CreatedDate,
                    ModifiedDate = author.ModifiedDate,
                    IsApproved = author.IsApproved,
                    Books = author.BookAuthors.Select(ba => new BookViewModel
                    {
                        Id = ba.Author.Id,
                        Name = ba.Author.Name,
                        Url = ba.Author.Url
                    }).ToList()
                });
            }
            AuthorListViewModel authorListViewModel = new AuthorListViewModel
            {
                Authors = authors,
                ApprovedStatus = true
            };
            return View("Index", authorListViewModel);
        }

        #endregion
        #region Yeni Kayıt
        [HttpGet]
        public IActionResult Create()
        {
            AuthorAddViewModel authorAddViewModel = new AuthorAddViewModel();
            return View(authorAddViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(AuthorAddViewModel authorAddViewModel)
        {
            if (ModelState.IsValid)
            {
                Author author = new Author
                {
                    Name = authorAddViewModel.Name,
                    Gender = authorAddViewModel.Gender,
                    Url = Jobs.GetUrl(authorAddViewModel.Name),
                    IsApproved = authorAddViewModel.IsApproved,
                    CreatedDate = DateTime.Now,
                    ModifiedDate = DateTime.Now,
                    About=authorAddViewModel.About
                };
                await _authorService.CreateAsync(author);
                return RedirectToAction("Index");
            }
            return View(authorAddViewModel);
        }

        #endregion
        #region Kayıt Güncelleme
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            Author author = await _authorService.GetByIdAsync(id);
            AuthorUpdateViewModel authorUpdateViewModel = new AuthorUpdateViewModel()
            {
                Id = author.Id,
                Name = author.Name,
                Gender = author.Gender,
                ModifiedDate = author.ModifiedDate,
                IsApproved = author.IsApproved,
                About=author.About
            };

            return View(authorUpdateViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(AuthorUpdateViewModel authorUpdateViewModel)
        {
            if (ModelState.IsValid)
            {
                Author author = await _authorService.GetByIdAsync(authorUpdateViewModel.Id);
                author.Name = authorUpdateViewModel.Name;
                author.Gender = authorUpdateViewModel.Gender;
                author.Url = Jobs.GetUrl(authorUpdateViewModel.Name);
                author.IsApproved = authorUpdateViewModel.IsApproved;
                author.ModifiedDate = DateTime.Now;
                author.About = authorUpdateViewModel.About;
                _authorService.Update(author);

                return RedirectToAction("Index");
            }
            return View(authorUpdateViewModel);
        }

        #endregion
        #region Kayıt Silme
        public async Task<IActionResult> Delete(int id)
        {
            Author deletedAuthor = await _authorService.GetByIdAsync(id);
            if (deletedAuthor != null)
            {
                _authorService.Delete(deletedAuthor);
            }

            return RedirectToAction("Index");
        }
        #endregion
        #region Onaylı
        public async Task<IActionResult> UpdateIsApproved(int id, bool ApprovedStatus)
        {
            Author author = await _authorService.GetByIdAsync(id);
            if (author != null)
            {
                author.IsApproved = !author.IsApproved;
                _authorService.Update(author);
            }
            AuthorListViewModel authorListViewModel = new AuthorListViewModel()
            {
                ApprovedStatus = ApprovedStatus
            };
            return RedirectToAction("Index", authorListViewModel);  
        }
        #endregion
    }
}

BooksApp/BooksApp.MVC/Areas/Admin/Controllers/BooksController.cs
using BooksApp.Business.Abstract;
using BooksApp.Core;
using BooksApp.Data.Abstract;
using BooksApp.Data.Concrete.EfCore;
using BooksApp.Entity.Concrete;
using BooksApp.MVC.Areas.Admin.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BooksApp.MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class BooksController : Controller
    {
        private IBookService _bookService;
        private ICategoryService _categoryService;
        private IImageService _imageService;
        private IAuthorService _authorService;

        public BooksController(IBookService bookService, ICategoryService categoryService, IImageService imageService, IAuthorService authorService)
        {
            _bookService = bookService;
            _categoryService = categoryService;
            _imageService = imageService;
            _authorService = authorService;
        }


        #region Listeleme
        public async Task<IActionResult> Index(BookListViewModel bookListViewModel)
        {
            List<Book> bookList;
            if (bookListViewModel.Books == null)
            {
                bookList = await _bookService.GetAllBooksFullDataAsync(bookListViewModel.ApprovedStatus);
                List<BookViewModel> books = new List<BookViewModel>();
                foreach (var book in bookList)
                {
                    books.Add(new BookViewModel
                    {
                        Id = book.Id,
                        Name = book.Name,
                        Stock = book.Stock,
                        Price = book.Price,
                        PageCount = book.PageCount,
                        EditionYear = book.EditionYear,
                        EditionNumber = book.EditionNumber,
                        CreatedDate = book.CreatedDate,
                        ModifiedDate = book.ModifiedDate,
                        IsApproved = book.IsApproved,
                        Categories = book.BookCategories.Select(bc => new CategoryViewModel
                        {
                            Id = bc.Category.Id,
                            Name = bc.Category.Name,
                            Url = bc.Category.Url
                        }).ToList(),
                        Authors = book.BookAuthors.Select(ba => new AuthorViewModel
                        {
                            Id = ba.Author.Id,
                            Name = ba.Author.Name,
                            Url = ba.Author.Url
                        }).ToList(),
                        Images = book.Images
                    });
                }
                bookListViewModel.Books = books;
            }
            return View(bookListViewModel);
        }
        public async Task<IActionResult> GetBooksByAuthor(int id)
        {
            List<Book> bookList = await _bookService.GetBooksByAuthor(id);
            List<BookViewModel> books = new List<BookViewModel>();
            foreach (var book in bookList)
            {
                books.Add(new BookViewModel
                {
                    Id = book.Id,
                    Name = book.Name,
                    Stock = book.Stock,
                    Price = book.Price,
                    PageCount = book.PageCount,
                    EditionYear = book.EditionYear,
                    EditionNumber = book.EditionNumber,
                    CreatedDate = book.CreatedDate,
                    ModifiedDate = book.ModifiedDate,
                    IsApproved = book.IsApproved,
                    Categories = book.BookCategories.Select(bc => new CategoryViewModel
                    {
                        Id = bc.Category.Id,
                        Name = bc.Category.Name,
                        Url = bc.Category.Url
                    }).ToList(),
                    Authors = book.BookAuthors.Select(ba => new AuthorViewModel
                    {
                        Id = ba.Author.Id,
                        Name = ba.Author.Name,
                        Url = ba.Author.Url
                    }).ToList(),
                    Images = book.Images
                });
            }
            BookListViewModel bookListViewModel = new BookListViewModel
            {
                Books = books,
                ApprovedStatus = true
            };
            return View("Index", bookListViewModel);
        }

        #endregion
        #region Yeni Kayıt
        [HttpGet]
        
        public async Task<IActionResult> Create()
        {
            BookAddViewModel bookAddViewModel = new BookAddViewModel
            {
                Categories = await _categoryService.GetCategoriesAsync(true),
                Authors = await _authorService.GetAllAsync()
            };

            return View(bookAddViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(BookAddViewModel bookAddViewModel)
        {
            if (ModelState.IsValid)
            {
                Book book = new Book
                {
                    Name = bookAddViewModel.Name,
                    Stock = bookAddViewModel.Stock,
                    PageCount = bookAddViewModel.PageCount,
                    Price = bookAddViewModel.Price,
                    EditionNumber = bookAddViewModel.EditionNumber,
                    EditionYear = bookAddViewModel.EditionYear,
                    Url = Jobs.GetUrl(bookAddViewModel.Name),
                    IsApproved = true,
                    CreatedDate = DateTime.Now,
                    ModifiedDate = DateTime.Now,
                    Summary=bookAddViewModel.Summary
                };
                List<Image> images = bookAddViewModel.Images.Select(i => new Image
                {
                    CreatedDate = DateTime.Now,
                    ModifiedDate = DateTime.Now,
                    IsApproved = true,
                    Url = Jobs.UploadImage(i)
                }).ToList();

                await _bookService.CreateBook(book, bookAddViewModel.SelectedCategories, bookAddViewModel.SelectedAuthors, images);
                TempData["Message"] = Jobs.CreateMessage("Başarılı", "Kitap başarıyla kaydedilmiştir.", "success");
                return RedirectToAction("Index");
            }
            bookAddViewModel.Categories = await _categoryService.GetCategoriesAsync(true);
            bookAddViewModel.Authors = await _authorService.GetAllAsync();
            TempData["Message"] = Jobs.CreateMessage("HATA!", "Kayıt sırasında bir hata oluştu, kontrol edip yeniden deneyiniz!", "warning");
            return View(bookAddViewModel);
        }

        #endregion
        #region Kayıt Güncelleme
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            Book book = await _bookService.GetBookFullDataAsync(id);
            BookUpdateViewModel bookUpdateViewModel = new BookUpdateViewModel()
            {
                Id = book.Id,
                Name = book.Name,
                Stock = book.Stock,
                PageCount = book.PageCount,
                EditionNumber = book.EditionNumber,
                EditionYear = book.EditionYear,
                Price = book.Price,
                ModifiedDate = book.ModifiedDate,
                IsApproved = book.IsApproved,
                Summary=book.Summary,
                ImageList = book.Images.Select(i => new Image
                {
                    Id = i.Id,
                    Url = i.Url
                }).ToList(),
                SelectedCategories = book.BookCategories.Select(i => i.Category.Id).ToArray(),
                SelectedAuthors = book.BookAuthors.Select(i => i.Author.Id).ToArray()
            };
            bookUpdateViewModel.Categories = await _categoryService.GetCategoriesAsync(true);
            bookUpdateViewModel.Authors = await _authorService.GetAllAsync();
            return View(bookUpdateViewModel);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(BookUpdateViewModel bookUpdateViewModel)
        {
            if (ModelState.IsValid)
            {
                Book book = await _bookService.GetBookFullDataAsync(bookUpdateViewModel.Id);
                book.Name = bookUpdateViewModel.Name;
                book.Url = Jobs.GetUrl(bookUpdateViewModel.Name);
                book.IsApproved = bookUpdateViewModel.IsApproved;
                book.ModifiedDate = DateTime.Now;
                book.Stock = bookUpdateViewModel.Stock;
                book.PageCount = bookUpdateViewModel.PageCount;
                book.EditionNumber = bookUpdateViewModel.EditionNumber;
                book.EditionYear = bookUpdateViewModel.EditionYear;
                book.Price = bookUpdateViewModel.Price;
                book.Summary = bookUpdateViewModel.Summary;

                if (bookUpdateViewModel.Images != null)
                {
                    List<Image> images = bookUpdateViewModel.Images.Select(i => new Image
                    {
                        CreatedDate = DateTime.Now,
                        ModifiedDate = DateTime.Now,
                        IsApproved = true,
                        Url = Jobs.UploadImage(i),
                        BookId = book.Id
                    }).ToList();
                    foreach (var item in images)
                    {
                        await _imageService.CreateAsync(item);
                    }
                }
                else if (_imageService.ImageCount(book.Id) == 0)
                {
                    bookUpdateViewModel.Categories = await _categoryService.GetCategoriesAsync(true);
                    bookUpdateViewModel.Images = new List<IFormFile>();
                    bookUpdateViewModel.ImageList = new List<Image>();

                    return View(bookUpdateViewModel);
                }

BooksApp/BooksApp.MVC/Areas/Admin/Views/Books/Create.cshtml
@model BookAddViewModel
<h1 class="display-6 mt-2">Yeni Kitap</h1>
<hr />

<form asp-area="Admin"
      asp-controller="Books"
      asp-action="Create"
      method="post"
      enctype="multipart/form-data">
    <div class="row">
        <div class="col-9">
            <div class="row">
                <div class="col">
                    <div class="mb-3">
                        <label class="form-label" asp-for="Name"></label>
                        <input class="form-control" asp-for="Name">
                        <span class="text-danger" asp-validation-for="Name"></span>
                    </div>
                    <div class="mb-3">
                        <label class="form-label" asp-for="Stock"></label>
                        <input class="form-control" asp-for="Stock">
                        <span class="text-danger" asp-validation-for="Stock"></span>
                    </div>
                    <div class="mb-3">
                        <label class="form-label" asp-for="Price"></label>
                        <input class="form-control" asp-for="Price">
                        <span class="text-danger" asp-validation-for="Price"></span>
                    </div>
                    <div class="mb-3">
                        <label class="form-label" asp-for="PageCount"></label>
                        <input class="form-control" asp-for="PageCount">
                        <span class="text-danger" asp-validation-for="PageCount"></span>
                    </div>

                </div>
                <div class="col">
                    <div class="mb-3">
                        <label class="form-label" asp-for="EditionYear"></label>
                        <input class="form-control" asp-for="EditionYear">
                        <span class="text-danger" asp-validation-for="EditionYear"></span>
                    </div>
                    <div class="mb-3">
                        <label class="form-label" asp-for="EditionNumber"></label>
                        <input class="form-control" asp-for="EditionNumber">
                        <span class="text-danger" asp-validation-for="EditionNumber"></span>
                    </div>
                    <div class="mb-3 form-check">
                        <input type="checkbox" class="form-check-input" asp-for="IsApproved">
                        <label class="form-check-label" asp-for="IsApproved"></label>
                    </div>
                    <div class="mb-3">
                        <input type="file" asp-for="Images" class="form-control" accept="image/" multiple />
                        <span class="text-danger" asp-validation-for="Images"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="mb-3">
                        <label class="form-label" asp-for="Summary"></label>
                        <textarea class="form-control" asp-for="Summary" id="editor"></textarea>
                        <span class="text-danger" asp-validation-for="Summary"></span>
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Kaydet</button>
        </div>
        <div class="col-3">
            <h5>Kategori Seç</h5>
            @foreach (var category in Model.Categories)
            {
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" name="SelectedCategories" value="@category.Id" @if(Model.SelectedCategories!=null){
                       @(Model.SelectedCategories.Any(sc=>sc==category.Id) ? "checked" : "")
                       }>
                    <label class="form-check-label">@category.Name</label>
                </div>
            }
            <span asp-validation-for="SelectedCategories" class="text-danger"></span>
            <h5>Yazar Seç</h5>
            @foreach (var author in Model.Authors)
            {
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" name="SelectedAuthors" value="@author.Id" @if(Model.SelectedAuthors!=null){
                       @(Model.SelectedAuthors.Any(sc=>sc==author.Id) ? "checked" : "")
                       }>
                    <label class="form-check-label">@author.Name</label>
                </div>
            }
            <span asp-validation-for="SelectedAuthors" class="text-danger"></span>
        </div>
    </div>

</form>
@section Scripts{
    @await Html.PartialAsync("_ValidationScriptsPartial");
    <script>
        CKEDITOR.replace('editor', {
            toolbar: [
                { name: 'colors', items: ['TextColor', 'BGColor'] },
                { name: 'styles', items: ['Format', 'Font', 'FontSize'] },
                { name: 'paraghraph', items: ['NumberedList', 'BulletedList'] }
            ]
        });
    </script>
}

@section Styles{
    <script src="//cdn.ckeditor.com/4.21.0/full/ckeditor.js"></script>
}

BooksApp/BooksApp.MVC/Areas/Admin/Views/Books/Delete.cshtml
@model BookViewModel
<h1 class="display-6 mt-2 text-danger">Kitap Siliniyor!</h1>
<hr />

<form asp-area="Admin"
      asp-controller="Books"
      asp-action="Delete"
      method="post">
    <div class="row">
        <div class="col-9">
            <div class="row">
                <div class="col">
                    <div class="mb-3">
                        <label class="form-label text-danger fw-bold">Kitap Adı:</label>
                        <label>@Model.Name</label>
                    </div>
                    <div class="mb-3">
                        <label class="form-label text-danger fw-bold">Stok Miktarı:</label>
                        <label>@Model.Stock</label>
                    </div>
                    <div class="mb-3">
                        <label class="form-label text-danger fw-bold">Fiyat:</label>
                        <label>@Model.Price</label>
                    </div>
                    <div class="mb-3">
                        <label class="form-label text-danger fw-bold">Sayfa Sayısı:</label>
                        <label>@Model.PageCount</label>
                    </div>

                </div>
                <div class="col">
                    <div class="mb-3">
                        <label class="form-label text-danger fw-bold">Basım Yılı:</label>
                        <label>@Model.EditionYear</label>
                    </div>
                    <div class="mb-3">
                        <label class="form-label text-danger fw-bold">Baskı No:</label>
                        <label>@Model.EditionNumber</label>
                    </div>
                    <div class="mb-3">
                        <label class="form-label text-danger fw-bold">Onay Durumu:</label>
                        <label>@(Model.IsApproved ? "Onaylı" : "Onaylı değil")</label>
                    </div>
                </div>
            </div>
            <div class="row mb-3">
                @foreach (var image in Model.Images)
                {
                    <div class="col-2">
                        <img src="~/images/books/@image.Url" class="img-thumbnail" width="100" alt="...">
                    </div>
                }
            </div>
            <button type="submit" class="btn btn-danger">Sil</button>

        </div>
        <div class="col-3">
            <h5 class="text-danger">Kategoriler</h5>
            <ul>
            @foreach (var category in Model.Categories)
            {
                <li>@category.Name</li>
            }
            </ul>
            <h5 class="text-danger">Yazarlar</h5>
            <ul>
                @foreach (var author in Model.Authors)
                {
                    <li>@author.Name</li>
                }
            </ul>
        </div>
    </div>

</form>
@section Scripts{
    @await Html.PartialAsync("_ValidationScriptsPartial");
}

BooksApp/BooksApp.MVC/Areas/Admin/Views/Books/Index.cshtml
@model BookListViewModel
@{
    List<BookViewModel> books = Model.Books;
}

<div class="container-fluid mt-3">
    <div class="d-flex justify-content-between align-items-center">
        <h1 class="display-6">Kitap Listesi</h1>
        <div class="d-flex flex-row align-items-end gap-5">
            <div>
                <form asp-area="Admin" asp-controller="Books" asp-action="Index"
                      class="mb-3 form-check" id="form-show-all">
                    <div class="form-check form-switch">
                        <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckChecked" asp-for="ApprovedStatus" onchange="document.getElementById('form-show-all').submit();">
                        <label class="form-check-label" for="flexSwitchCheckChecked">@(Model.ApprovedStatus ? "Pasifleri Göster" : "Aktifleri Göster")</label>
                    </div>
                </form>
            </div>
            <div>
                <a class="btn btn-success"
                   asp-area="Admin"
                   asp-controller="Books"
                   asp-action="Create">Kitap Ekle</a>
            </div>
        </div>
    </div>
    <hr />
    <table id="myDataTable" class="table table-bordered table-sm">
        <thead class="text-bg-success">
            <tr>
                <th width="80">Id</th>
                <th>Kitap Adı</th>
                <th>Onaylı?</th>
                <th>Yazarları</th>
                <th width="240">İşlemler</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var book in books)
            {
                <tr>
                    <td class="align-middle">@book.Id</td>
                    <td class="align-middle">@book.Name</td>
                    <td class="align-middle">
                        <form asp-area="Admin"
                          asp-controller="Books"
                          asp-action="UpdateIsApproved"
                          asp-route-id=@book.Id
                          class="form-check" id="form-isapproved-@book.Id">
                            <div class="form-check form-switch">
                                <input type="hidden" asp-for="ApprovedStatus">
                                <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckChecked" asp-for="@book.IsApproved" onchange="document.getElementById('form-isapproved-@book.Id').submit();">
                            </div>
                        </form>
                    </td>
                    <td>
                        <a 
                            asp-area="Admin"
                            asp-controller="Authors"
                            asp-action="GetAuthorsByBook"
                            asp-route-id=@book.Id
                            class="btn btn-link">(@book.Authors.Count)</a>
                    </td>
                    <td class="align-middle">
                        <a class="btn btn-warning btn-sm"
                       asp-area="Admin"
                       asp-controller="Books"
                       asp-action="Edit"
                       asp-route-id=@book.Id>Düzenle</a>
                        <a class="btn btn-outline-danger btn-sm"
                       asp-area="Admin"
                       asp-controller="Books"
                       asp-action="Delete"
                       asp-route-id=@book.Id>Sil</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

@section Styles{
    @await Html.PartialAsync("_DataTablesStylesPartialView")
}
@section Scripts{
    @await Html.PartialAsync("_DataTablesScriptsPartialView")
}